### ISSUE TITLE
Wish: per-volume retention

### ISSUE THREAD

**Issue by markstos** [tangerinedream/SnapshotExpirationUtility#1]
I'm taking nightly snapshots of many hosts and volumes. I'd like the snapshots of each vollume to be considered independently.   For a simple retention rule like "keep the last 60 days", this doesn't matter, but it matters for complex retention rules, like "keep the first snapshot for each month".

**Comment by markstos** [comment]
Would you be interested in a per-volume design if I worked on a pull request?

**Comment by tangerinedream** [comment]
I would be interested in seeing a design, although I suspect this may complicate things materially if I understand your request.  Are you thinking to have a retention policy rule per volume (I suspect this would be complex), or a retention policy across the board for all volumes (which it sort of does today)?

**Comment by markstos** [comment]
I'm thinking of one retention policy, applied to each volume, rather than across all volumes.

**Comment by tangerinedream** [comment]
I'd like to see your design for this.  I suspect it will be tedious, however, to manage this given the sheer number of volumes typically involved.  How would you manage assigning policies to individual volumes?

**Comment by markstos** [comment]
There may be some confusion. I meant to express there would be _one retention policy_, not per-volume policies. 

To rotate the backups, you go through each volume there are snapshots for, and then apply something like [grandfatherson](https://github.com/ecometrica/grandfatherson) to filter the backups for that volume.

Processing snapshots for multiple volumes could done concurrently, since the result for one volume doesn't depend on the result of processing another volume. 

If you need a different policy for some different volumes (Say, Database servers get special treatment), you could all the utility twice. In the first pass, select most volumes to process with the main policy. In the second pass, select just the database volumes that need a different retention policy.

**Comment by tangerinedream** [comment]
Hi,
I think there is a way forward that would work, and also be slightly more efficient: 
- Avoid the introduction of the Volume resource into the solution at all, and 
- reducing the # of API calls by not having to run the utility multiple times to accomplish the goal.

What is important is to decision on is exactly how to know what policy applies to a given snapshot.  If that information exists on the snapshot itself, this solution would work.  

Here is the design:
Snapshots contain a user defined TagKey and a user selected structed TagValue, which indicates the retention policy.  The TagValue must adhere to a formal naming convention, as the solution relies will need to interpret it for processing.

User will affix the TagValue, (e.g. 7.4.12 to indicate 7 daily, 4 weekly, and 12 monthly) to the Snapshot, thus applying the retention policy.  Snapshots can have any TagValue so long as it conforms to the convention (e.g. 14.0.0 for 14 daily, 0 weekly, and 0 monthly)

At runtime, the solution creates a unique Set of policies from the Snapshots (e.g. the TagValue) since at runtime the solution has no idea what policies exist.  Using the unique Set of policies, use GrandfatherFatherSon to generate "delete" list of dates.    

In concert to the unique Set of policies determination, bucket the snapshot IDs themselves by policy using the TagValue (e.g. all 7.4.12 snapshot id go into List A, 14.0.0. go into List B, etc..), capturing the Snapshot creation date in the same API call.

Using python Set operations, determine which snapshots are to be deleted and delete them.

This should work and provide a great deal of Flexibility for users of the software.

I have a few other things in process currently and so will need time, and prioritization.  If you want to contribute, please send a pull request and we can work off a separate branch.

**Comment by markstos** [comment]
@tangerinedream: Putting policies in snapshot tags sounds like a pain to me. I have about 700 snapshots now, but only two different policies I need to use with them.   I generate the snapshots automatically and _could_ automate putting extra tags on them, but I also anticipate changing the policy over time. If the polices were stored on the snapshots, I would need yet-another tool to change the policies embedded in the snapshots. 

On the other hand, the number and performance of API calls is not a particular consider.  Right now to delete snapshots with 2 different policies, I need to make:
- 2 "describe" calls to grab different lists of snapshots I want to process
  - 1 "delete" call per snapshot to prune.

Let's say I prune 30 snapshots one night. So that's 32 API calls.  I could "optimize" this to make only 31 calls with one "describe" call, but why?  The "cron job runs in the middle of night, takes just a few seconds to run and costs hardly anything as it is. 

Because I need to get this snapshot rotation working soon and because I know JavaScript better than that Python, I [ported grandfatherson](https://github.com/RideAmigosCorp/grandfatherson) to JavaScript and working on a JavaScript-based solution to this.

My "Lambda" code is largely done at this point and is in the debug/testing stage.

**Comment by markstos** [comment]
I've now published my own project which implements the features I wanted:
https://github.com/RideAmigosCorp/lambda-expire-snapshots

**Comment by tangerinedream** [comment]
@markstos What I like about your solution is the elegance of incorporation into Lambda, which is still on my roadmap.  The shortcoming I see in your solution, which you've already disagreed with me on, is relying on tags _not_ on the snapshot.  With that approach, when your instances are terminated, your existing snapshots will no longer be under any form of retention rules.  This is the issue that I've found with many solutions, and the reason this utility was required to be created in the first place.  

The retention rules need to be on the snapshots so that:
A) they can exist beyond the lifecycle of the instance that created them.  That's how the instance can be  recreated from the snapshot if you need it later, and
B) they need to be deleted at some point, for lifecycle/policy and cost management.

The good news is that if you choose, it would seem very straight forward for you to adopt those changes - if you so choose.

Good luck and I hope we can work together in the future!

**Comment by markstos** [comment]
@tangerinedream, I _am_ in favor of tags on the snapshot. I agree that a snapshot with tags is fairly worthless especially once the related volume is no longer available. 

I think the distinction we are discussing is parallel to the distinction between two types of AWS IAM policies: "in-line policies" and "managed policies". The best practice is usually to use "Managed Policies" where you define a policy once and given it a name. Then when you want to apply the policy, you refer it to by name instead of embedding the policy. When you want to change the policy, you can change it one place and the updated Managed Policy affects all the places it's been applied. 

Here are two concrete alternatives key/value to consider for snapshots:

```
 # In-line policy examples
 Retention-Policy: { "days": 2, "weeks": 3 }
 Retention-Policy: { "hours" : 48, "months" : 6 }

 # Managed Policy examples
Retention-Policy: default
Retention-Policy: customer-data
```

I'm in in favor of the second style tags which add a _semantic_ label about which retention-policy you want to apply. The defaults of the policy are defined elsewhere. In my case-- the `lambda-expire-snapshot` config file handles defining the snapshot tags you want to deal with as well as the retention policy you want to apply.

When I want to change the "default" retention rules, I don't have to update 700 snapshots, I just update the backup configuration file. 

I would welcome help maintaining `lambda-expire-snapshots` and would consider switching back to another tool in the future if and advantages.  My  hunch is that AWS is going to add a feature to define Lifecycle Policies on snapshots after a while, making all these tools obsolete.

**Comment by tangerinedream** [comment]
Hi @markstos, thanks for your reply as it does shed more light as to what you are thinking.  One thing I do want to make clear is that I'm saying the opposite to your second statement.  I absolutely DO think having the tagged snapshot is worthy, especially once the volume is terminated.  That is exactly when it's most valuable.  My example is 2 weeks after you terminate a workload (and it's associated volumes).  If you are asked to "restore" that workload for whatever reason, you'll be very happy you have it tagged.

I'm planning to do so work as relates to the Grandfather-Father-son piece shortly.  I'll let you know when I have something to share.

Thanks,
Gary
